# Generated by Django 2.2.16 on 2022-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220511_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, verbose_name='Код подтверждения'),
        ),
    ]
